["common"]
1 = {
    name = "Copper Sword",
    price = 10,
    description = "A common copper sword mass produced by an unknown smithy",
    droppable = true,
    inshop = true,
    tradable = true,
    stats = {
        attack = 4,
        speed = 2,
        defence = 3,
        health = 1,
        stamina = 0,
        iq = 0,
        luck = 0
    }
}
